dataset_args:
  dataset_path: sujet-ai/Sujet-Finance-Instruct-177k


trainer_args:
  output_dir: /outputs/sujet117k-llama7b-dp8/
  overwrite_output_dir: True
  save_steps: 750
  callback_after_n_steps: 750
  num_train_epochs: 4
  gradient_accumulation_steps: 8
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  remove_unused_columns: False
  # resume_from_checkpoint: True

privacy_args:
  target_epsilon: 8

model_args:
  architecture: llama
  pre_trained: True   # Start from a pre-trained checkpoint

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False